name: VasumiZjikaaTelos
favicon: null
layout_spectrum: 0
typography_spectrum: 0.15691
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#301608'
    - '#fcfdf5'
    - '#9b572f'
    - '#e17835'
    - '#9da800'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 0.8352896813303232
purpose: []
