name: VasumiZjikaaTelos
favicon: null
layout_spectrum: 0.5294137236196548
typography_spectrum: 0.01708895619958639
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.1515047235880047
  lightness: 0.44679287914186716
  saturation: 0.2834649817086756
  rhythmicContrast: 0.8352896813303232
purpose: []
